/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/wOfbq7jCo6F
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from 'next/link'
import { Button } from '@/components/ui/button'
import { Badge } from '@/components/ui/badge'
import { Separator } from '@/components/ui/separator'
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
} from '@/components/ui/dropdown-menu'
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs'
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
} from '@/components/ui/card'

export function Demo() {
  return (
    <div className="flex min-h-screen w-full flex-col bg-muted/40">
      <h2 className="text-center text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
        <div>UX</div>
      </h2>

      <main className="flex min-h-[calc(100vh_-_theme(spacing.16))] flex-1 flex-col gap-4 p-4 md:gap-8 md:p-10">
        <div className="mx-auto grid w-full max-w-6xl gap-2">
          <h1 className="text-3xl font-semibold">Deployments</h1>
        </div>
        <div className="mx-auto grid w-full max-w-6xl gap-6">
          <div className="grid gap-4 overflow-hidden rounded-lg border lg:gap-px lg:bg-gray-100">
            <div className="relative flex flex-col bg-background p-2 text-sm lg:flex-row">
              <div className="grid flex-1 gap-1 p-2">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    width="16"
                    height="16"
                    alt="Favicon"
                    className="rounded-full"
                  />
                  <div className="font-medium">www.example.com</div>
                </div>
                <div className="text-muted-foreground">
                  Production{' '}
                  <Badge variant="outline" className="bg-background">
                    Current
                  </Badge>
                </div>
              </div>
              <Separator className="my-2 lg:hidden" />
              <div className="grid flex-1 gap-1 p-2">
                <div className="flex items-center gap-2">
                  <GitCommitVerticalIcon className="h-4 w-4" />
                  <span className="line-clamp-1">
                    fix: auth issues for third-party integration
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <GitBranchIcon className="h-4 w-4" />
                  <span>main</span>
                </div>
              </div>
              <Separator className="my-2 lg:hidden" />
              <div className="grid flex-1 gap-1 p-2">
                <div className="flex items-center gap-2 text-muted-foreground">
                  17m ago by Raj
                </div>
              </div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="absolute right-4 top-4"
                  >
                    <MoveHorizontalIcon className="h-4 w-4" />
                    <span className="sr-only">Toggle menu</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuItem>View Deployment</DropdownMenuItem>
                  <DropdownMenuItem>Redeploy</DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem disabled>Rollback</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
            <div className="relative flex flex-col bg-background p-2 text-sm lg:flex-row">
              <div className="grid flex-1 gap-1 p-2">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    width="16"
                    height="16"
                    alt="Favicon"
                    className="rounded-full"
                  />
                  <div className="font-medium">app.example.com</div>
                </div>
                <div className="text-muted-foreground">Preview</div>
              </div>
              <Separator className="my-2 lg:hidden" />
              <div className="grid flex-1 gap-1 p-2">
                <div className="flex items-center gap-2">
                  <GitCommitVerticalIcon className="h-4 w-4" />
                  <span className="line-clamp-1">
                    feat: implement action logging
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <GitBranchIcon className="h-4 w-4" />
                  <span>Joe/logging</span>
                </div>
              </div>
              <Separator className="my-2 lg:hidden" />
              <div className="grid flex-1 gap-1 p-2">
                <div className="flex items-center gap-2 text-muted-foreground">
                  32m ago by Joe
                </div>
              </div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="absolute right-4 top-4"
                  >
                    <MoveHorizontalIcon className="h-4 w-4" />
                    <span className="sr-only">Toggle menu</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuItem>View Deployment</DropdownMenuItem>
                  <DropdownMenuItem>Redeploy</DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem disabled>Rollback</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
            <div className="relative flex flex-col bg-background p-2 text-sm lg:flex-row">
              <div className="grid flex-1 gap-1 p-2">
                <div className="flex items-center gap-2">
                  <img
                    src="/placeholder.svg"
                    width="16"
                    height="16"
                    alt="Favicon"
                    className="rounded-full"
                  />
                  <div className="font-medium">docs.example.com</div>
                </div>
                <div className="text-muted-foreground">Preview</div>
              </div>
              <Separator className="my-2 lg:hidden" />
              <div className="grid flex-1 gap-1 p-2">
                <div className="flex items-center gap-2">
                  <GitCommitVerticalIcon className="h-4 w-4" />
                  <span className="line-clamp-1">
                    feat: implement history sidebar
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <GitBranchIcon className="h-4 w-4" />
                  <span>Chad/history-sidebar</span>
                </div>
              </div>
              <Separator className="my-2 lg:hidden" />
              <div className="grid flex-1 gap-1 p-2">
                <div className="flex items-center gap-2 text-muted-foreground">
                  1 day ago by Chad
                </div>
              </div>
              <DropdownMenu>
                <DropdownMenuTrigger asChild>
                  <Button
                    variant="ghost"
                    size="icon"
                    className="absolute right-4 top-4"
                  >
                    <MoveHorizontalIcon className="h-4 w-4" />
                    <span className="sr-only">Toggle menu</span>
                  </Button>
                </DropdownMenuTrigger>
                <DropdownMenuContent align="end">
                  <DropdownMenuItem>View Deployment</DropdownMenuItem>
                  <DropdownMenuItem>Redeploy</DropdownMenuItem>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem disabled>Rollback</DropdownMenuItem>
                </DropdownMenuContent>
              </DropdownMenu>
            </div>
          </div>
          <Tabs defaultValue="integrations">
            <TabsList className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <TabsTrigger value="integrations">Integrations</TabsTrigger>
                <TabsTrigger value="deployments">Deployments</TabsTrigger>
              </div>
              <div className="flex items-center gap-2">
                <Button variant="outline" size="sm" className="h-8 gap-1">
                  <PlusIcon className="h-4 w-4" />
                  <span>New Deployment</span>
                </Button>
              </div>
            </TabsList>
            <TabsContent value="deployments" />
            <TabsContent value="integrations">
              <Card className="p-6">
                <CardHeader>
                  <CardTitle>Integrations</CardTitle>
                  <CardDescription>
                    Connect your favorite tools and services to your
                    deployments.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="grid gap-4">
                    <div className="flex items-center gap-4">
                      <div className="flex aspect-square w-12 items-center justify-center rounded-md bg-muted">
                        <GithubIcon className="h-6 w-6" />
                      </div>
                      <div className="grid flex-1 gap-1">
                        <div className="font-medium">GitHub</div>
                        <div className="text-sm text-muted-foreground">
                          Integrate your GitHub repository for automatic
                          deployments.
                        </div>
                      </div>
                      <Button variant="outline" size="sm" className="h-8 gap-1">
                        Connect
                      </Button>
                    </div>
                    <div className="flex items-center gap-4">
                      <div className="flex aspect-square w-12 items-center justify-center rounded-md bg-muted">
                        <SlackIcon className="h-6 w-6" />
                      </div>
                      <div className="grid flex-1 gap-1">
                        <div className="font-medium">Slack</div>
                        <div className="text-sm text-muted-foreground">
                          Get deployment notifications in your Slack channels.
                        </div>
                      </div>
                      <Button variant="outline" size="sm" className="h-8 gap-1">
                        Connect
                      </Button>
                    </div>
                    <div className="flex items-center gap-4">
                      <div className="flex aspect-square w-12 items-center justify-center rounded-md bg-muted">
                        <DogIcon className="h-6 w-6" />
                      </div>
                      <div className="grid flex-1 gap-1">
                        <div className="font-medium">Datadog</div>
                        <div className="text-sm text-muted-foreground">
                          Monitor your deployments with Datadog.
                        </div>
                      </div>
                      <Button variant="outline" size="sm" className="h-8 gap-1">
                        Connect
                      </Button>
                    </div>
                  </div>
                </CardContent>
              </Card>
            </TabsContent>
          </Tabs>
        </div>
      </main>
    </div>
  )
}

function DogIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 5.172C10 3.782 8.423 2.679 6.5 3c-2.823.47-4.113 6.006-4 7 .08.703 1.725 1.722 3.656 1 1.261-.472 1.96-1.45 2.344-2.5" />
      <path d="M14.267 5.172c0-1.39 1.577-2.493 3.5-2.172 2.823.47 4.113 6.006 4 7-.08.703-1.725 1.722-3.656 1-1.261-.472-1.855-1.45-2.239-2.5" />
      <path d="M8 14v.5" />
      <path d="M16 14v.5" />
      <path d="M11.25 16.25h1.5L12 17l-.75-.75Z" />
      <path d="M4.42 11.247A13.152 13.152 0 0 0 4 14.556C4 18.728 7.582 21 12 21s8-2.272 8-6.444c0-1.061-.162-2.2-.493-3.309m-9.243-6.082A8.801 8.801 0 0 1 12 5c.78 0 1.5.108 2.161.306" />
    </svg>
  )
}

function FrameIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="22" x2="2" y1="6" y2="6" />
      <line x1="22" x2="2" y1="18" y2="18" />
      <line x1="6" x2="6" y1="2" y2="22" />
      <line x1="18" x2="18" y1="2" y2="22" />
    </svg>
  )
}

function GitBranchIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="6" x2="6" y1="3" y2="15" />
      <circle cx="18" cy="6" r="3" />
      <circle cx="6" cy="18" r="3" />
      <path d="M18 9a9 9 0 0 1-9 9" />
    </svg>
  )
}

function GitCommitVerticalIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 3v6" />
      <circle cx="12" cy="12" r="3" />
      <path d="M12 15v6" />
    </svg>
  )
}

function GithubIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4" />
      <path d="M9 18c-4.51 2-5-2-7-2" />
    </svg>
  )
}

function MoveHorizontalIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="18 8 22 12 18 16" />
      <polyline points="6 8 2 12 6 16" />
      <line x1="2" x2="22" y1="12" y2="12" />
    </svg>
  )
}

function PlusIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}

function SlackIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="3" height="8" x="13" y="2" rx="1.5" />
      <path d="M19 8.5V10h1.5A1.5 1.5 0 1 0 19 8.5" />
      <rect width="3" height="8" x="8" y="14" rx="1.5" />
      <path d="M5 15.5V14H3.5A1.5 1.5 0 1 0 5 15.5" />
      <rect width="8" height="3" x="14" y="13" rx="1.5" />
      <path d="M15.5 19H14v1.5a1.5 1.5 0 1 0 1.5-1.5" />
      <rect width="8" height="3" x="2" y="8" rx="1.5" />
      <path d="M8.5 5H10V3.5A1.5 1.5 0 1 0 8.5 5" />
    </svg>
  )
}

function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
