/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5KhfmFoMwuo
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from 'next/link'
import { Input } from '@/components/ui/input'
import { Button } from '@/components/ui/button'
import {
  Card,
  CardHeader,
  CardTitle,
  CardDescription,
  CardContent,
  CardFooter,
} from '@/components/ui/card'
import { Demo } from '@/components/Demo'
// import Spline from '@splinetool/react-spline'
import ComparisionTable from './ComparisionTable'

export function Landing() {
  return (
    <div className="min-h-dvh flex flex-col">
      <main className="flex-1">
        <section className="w-full border-y pt-12 md:pt-24 lg:pt-32">
          <div className="space-y-10 px-4 md:px-6 xl:space-y-16">
            <div className="mx-auto grid max-w-[1300px] gap-4 px-4 sm:px-6 md:grid-cols-2 md:gap-16 md:px-10">
              <div>
                <h1 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
                  Write the code. Forget the cloud.
                </h1>
                <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl">
                  Vercel, Heroku Ease + AWS Affordability: Scale applications
                  without fighting VMs at 2 am.{' '}
                </p>
                <div className="mt-6 w-full max-w-sm space-y-2">
                  <form className="flex gap-2">
                    <Input
                      type="email"
                      placeholder="Enter your email"
                      className="max-w-lg flex-1"
                    />
                    <Button type="submit">Join Waitlist</Button>
                  </form>
                  <p className="text-xs text-muted-foreground">
                    Sign up to get notified when we launch.{' '}
                    <Link
                      href="#"
                      className="underline underline-offset-2"
                      prefetch={false}
                    >
                      Terms &amp; Conditions
                    </Link>
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-start justify-center space-y-4">
                {/* <Spline scene="https://prod.spline.design/BlifPelOQWyhJHBR/scene.splinecode" /> */}

                {/* <SplineViewer url="https://my.spline.design/glassdonut-3fd65cbafe916e0d15c13978ac70500a/" /> */}
              </div>
            </div>
          </div>
        </section>
        {/* <section className="w-full pt-12 md:pt-24 lg:pt-32 border-y">
          <div className="px-4 md:px-6 space-y-10 xl:space-y-16">
            <div className="grid max-w-[1300px] mx-auto gap-4 px-4 sm:px-6 md:px-10 md:grid-cols-2 md:gap-16">
              <div className="overflow-x-auto"> */}
        <section>
          <div>
            <div>
              <div>
                <ComparisionTable />
              </div>
            </div>
          </div>
        </section>

        <section>
          <Demo />
        </section>

        <section className="w-full bg-primary py-12 text-primary-foreground md:py-24 lg:py-32">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                Writing code is the only thing you should be worrying about, let
                us handle the rest
              </h2>
              <p className="mx-auto max-w-[700px] md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                From SSL certificates to CI/CD, we have got you covered. Focus
                on building your app, and let us take care of the
                infrastructure.
              </p>
            </div>
            <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
              <Card className="bg-primary-foreground text-primary">
                <CardHeader>
                  <CardTitle>Custom URL for Preview</CardTitle>
                  <CardDescription>
                    Preview your work with a unique URL.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-col gap-4">
                    <p>Automatically provision a new URL for each preview.</p>
                    <div className="items- flex" />
                  </div>
                </CardContent>
              </Card>

              <Card className="bg-primary-foreground text-primary">
                <CardHeader>
                  <CardTitle>Auto-SSL for Your Domains</CardTitle>
                  <CardDescription>
                    Secure your site with SSL/TLS encryption.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-col gap-4">
                    <p>
                      We provide and renew SSL/TLS certificates for your domain
                      automatically, ensuring encrypted data transmission.
                    </p>
                    <div className="items- flex" />
                  </div>
                </CardContent>
              </Card>

              <Card className="bg-primary-foreground text-primary">
                <CardHeader>
                  <CardTitle>Automatic GitHub CI/CD</CardTitle>
                  <CardDescription>
                    Deploy to production with one git push.
                  </CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-col gap-4">
                    <p>Our GitHub app handles the CI/CD process for you.</p>
                    <div className="items- flex" />
                  </div>
                </CardContent>
              </Card>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function CheckIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}

function CrossIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M11 2a2 2 0 0 0-2 2v5H4a2 2 0 0 0-2 2v2c0 1.1.9 2 2 2h5v5c0 1.1.9 2 2 2h2a2 2 0 0 0 2-2v-5h5a2 2 0 0 0 2-2v-2a2 2 0 0 0-2-2h-5V4a2 2 0 0 0-2-2h-2z" />
    </svg>
  )
}

function MountainIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}

function XIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
